CREATE TABLE BEDUERFNISZUORDNUNG (
    BEDUERFNISZUORDNUNG_ID INT,
    SSN                    INT NOT NULL REFERENCES PERSON(SSN),
    BEDUERFNIS_ID          INT NOT NULL REFERENCES BEDUERFNIS(BEDUERFNIS_ID),

    PRIMARY KEY (BEDUERFNISZUORDNUNG_ID)
);


INSERT INTO Beduerfniszuordnung (Beduerfniszuordnung_ID, SSN, Beduerfnis_ID) VALUES
(1, 1001, 1),
(2, 1001, 2),
(3, 1002, 3),
(4, 1003, 4),
(5, 1004, 5),
(6, 1005, 6),
(7, 1007, 7);
