CREATE TABLE AKTIVITAETSADRESSE (
    AKTIVITAETSADRESSE_ID INT,
    ADRESSE_ID            INT NOT NULL REFERENCES ADRESSE(ADRESSE_ID),
    AKTIVITAET_ID         INT NOT NULL REFERENCES AKTIVITAET(AKTIVITAET_ID),

    PRIMARY KEY (AKTIVITAETSADRESSE_ID)
);


INSERT INTO Aktivitaetsadresse (Aktivitaetsadresse_ID, Adresse_ID, Aktivitaet_ID) VALUES
(1, 1, 1),
(2, 2, 2),
(3, 3, 3),
(4, 4, 4),
(5, 5, 5),
(6, 6, 6),
(7, 7, 7);
