CREATE TABLE GEMACHTE_AKTIVITAET (
    GEMACHTE_AKTIVITAET_ID INT,
    SSN                    INT NOT NULL REFERENCES PERSON(SSN),
    AKTIVITAET_ID          INT NOT NULL REFERENCES AKTIVITAET(AKTIVITAET_ID),

    PRIMARY KEY (GEMACHTE_AKTIVITAET_ID)
);


INSERT INTO GEMACHTE_AKTIVITAET (GEMACHTE_AKTIVITAET_ID, SSN, Aktivitaet_ID) VALUES
(1, 1001, 1),
(2, 1003, 2),
(3, 1002, 3),
(4, 1004, 4),
(5, 1005, 5),
(6, 1006, 6),
(7, 1007, 7);
